import Input from "../components/Input";
import Head from "next/head";
import { LeftArrowIcon } from "public/icons/LeftArrow";
import { RightArrowIcon } from "public/icons/RightArrow";
import { useState } from "react";

const InitialFormData = {
  name: "",
  age: 0,
  gender: null,
  jobLocationPreference: null,
  salaryExpectation: null,
  qualification: null,
  skills: [],
  extraCuricularActivites: [],
  photo: null,
  resume: null,
};

export default function Home() {
  const [formData, setFormData] = useState(InitialFormData);
  const [quesNo, setQuesNo] = useState(0);
  const noOfQues = DATA.questions.length;

  const nextQuestion = () =>
    setQuesNo((prev) => Math.min(noOfQues - 1, prev + 1));
  const previouQuestion = () => setQuesNo((prev) => Math.max(0, prev - 1));

  const handleSubmit = (e) => {
    e.preventDefault();

    // Handle form submission here
  };

  return (
    <>
      <Head>
        <title>Survey App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fullscreen flex flex-col items-center">
        <h1 className="text-3xl font-bold w-full bg-neutral text-white p-4 px-8">
          {DATA.setting.title}
        </h1>

        <form
          onSubmit={handleSubmit}
          className="flex-1 w-11/12 max-w-3xl p-2 flex flex-col justify-center"
        >
          {DATA.questions.map((question, i) => (
            <div
              className={`flex flex-col gap-2 ${quesNo != i && "hidden"}`}
              key={question.id}
            >
              <h3 className="text-xl font-semibold">Question {i + 1}</h3>
              <Input {...question} />
            </div>
          ))}
          {quesNo == noOfQues - 1 ? (
            <button
              type="submit"
              className="btn btn-primary mt-6 self-start w-1/3"
            >
              submit
            </button>
          ) : (
            <button
              onClick={nextQuestion}
              type="button"
              className="btn mt-6 self-start w-1/3"
            >
              next
            </button>
          )}
        </form>

        <div className="border-t-2 flex gap-4 p-4 w-full">
          <div className="flex-1 flex items-center gap-8">
            <progress
              className="progress w-56"
              value={((quesNo + 1) / noOfQues) * 100}
              max="100"
            ></progress>
            <span>
              {quesNo + 1} / {noOfQues}
            </span>
          </div>
          <button
            data-tip="Previous"
            disabled={quesNo == 0}
            className={`btn tooltip ${quesNo == 0 && "btn-disabled"}`}
            onClick={previouQuestion}
          >
            <LeftArrowIcon />
          </button>
          <button
            data-tip="Next"
            disabled={quesNo == noOfQues}
            className={`btn tooltip ${
              quesNo == noOfQues - 1 && "btn-disabled"
            }`}
            onClick={nextQuestion}
          >
            <RightArrowIcon />
          </button>
        </div>
      </main>
    </>
  );
}

const DATA = {
  setting: { title: "Intern Application Form", favicon: "" },
  questions: [
    { id: 90, question_text: "Your Email ?", question_type: 4, required: 1 },
    { id: 91, question_text: "Your Age ?", question_type: 4, required: 0 },
    {
      id: 92,
      question_text: "Your Gender ?",
      question_type: 1,
      required: 1,
      choices: [
        { id: 777, choice_text: "Male" },
        { id: 778, choice_text: "Female" },
        { id: 779, choice_text: "Other" },
      ],
    },
    {
      id: 93,
      question_text: "Your prefered job location ?",
      question_type: 1,
      required: 0,
      choices: [
        { id: 780, choice_text: "Work from home" },
        { id: 781, choice_text: "Work in office" },
        { id: 782, choice_text: "work in hybrid way" },
      ],
    },
    {
      id: 94,
      question_text: "Your Salary Expectation (CTC in rupees)?",
      question_type: 2,
      required: 1,
      choices: [
        { id: 783, choice_text: "2-3 lakh" },
        { id: 784, choice_text: "4-5 lakh" },
        { id: 785, choice_text: "5-6 lakh" },
        { id: 786, choice_text: "6-7 lakh" },
      ],
    },
    {
      id: 95,
      question_text: "Your Educational Qualification ?",
      question_type: 2,
      required: 0,
      choices: [
        { id: 787, choice_text: "Illiterate" },
        { id: 788, choice_text: "Below 10th standard" },
        { id: 789, choice_text: "10th passed" },
        { id: 790, choice_text: "12th passed" },
        { id: 791, choice_text: "Undergraduate" },
        { id: 792, choice_text: "Postgraduate" },
      ],
    },
    {
      id: 96,
      question_text: "Your Skills",
      question_type: 3,
      required: 1,
      choices: [
        { id: 793, choice_text: "Node.js" },
        { id: 794, choice_text: "ReactJS" },
        { id: 795, choice_text: "Mongodb" },
        { id: 796, choice_text: "Express" },
      ],
    },
    {
      id: 97,
      question_text: "Your Extra Activities",
      question_type: 3,
      required: 0,
      choices: [
        { id: 797, choice_text: "Cricket" },
        { id: 798, choice_text: "Football" },
        { id: 799, choice_text: "Tenis" },
        { id: 800, choice_text: "Badminton" },
      ],
    },
    { id: 98, question_text: "Your Photo", question_type: 5, required: 1 },
    { id: 99, question_text: "Your CV in pdf", question_type: 5, required: 0 },
  ],
};
